repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "-rn", # Só apresentar mensagens
            "-sn", # Não apresentar o score, gerado pelo pylint informando se está tudo bem ou não (só queremos os erros)
            "--rcfile=.pylintrc", # Indica qual o arquivo de configuração pylint
            "--load-plugins=pylint.extensions.docparams", # Se precisar algum plugin, seja adicionado
          ]